name: pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v4

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar uv
        run: python -m pip install uv

      - name: Instalar dependências
        run: uv sync --dev

      - name: Executar o linter
        run: uv run task lint

      - name: Executar os testes
        run: uv run task test
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
